spring:
  resources:
    static-locations:
    - file:///D:/repository/web-resources/web-resources/

server:
  port: 8081
  servlet:
    context-path: /identity-service

# debug: true
   
security:
  oauth2:
    client:
      authorized-grant-types:
      - authorization_code
      - refresh_token
      - password
      - client_credentials
      client-id: SampleClientId
      client-secret: secret
      scope:
      - openid
      - read
      - write
    
